name: firebase-testing
on: [push]
jobs:
  install-gcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Set up gcloud Cloud SDK environment
  # You may pin to the exact commit or the version.
  # uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
    # Version of the gcloud SDK to install. If unspecified or set to "latest", the latest available gcloud SDK version for the target platform will be installed. Example: "290.0.1".
          version: latest
    # Service account email address to use for authentication. This is required for legacy .p12 keys but can be omitted for .json keys. This is usually of the format <name>@<project-id>.iam.gserviceaccount.com.
        
    # Service account key to use for authentication. This should be the JSON formatted private key which can be exported from the Cloud Console. The value can be raw or base64-encoded.
          service_account_key: gonative-test-suite-firebase-adminsdk-xc0ob-200504b941.json
    # ID of the Google Cloud project. If provided, this will configure gcloud to use this project ID by default for commands. Individual commands can still override the project using the --project flag which takes precedence.
          project_id: gonative-test-suite
    # Export the provided credentials as Google Default Application Credentials. This will make the credentials available to later steps via the GOOGLE_APPLICATION_CREDENTIALS environment variable. Future steps that consume Default Application Credentials will automatically detect and use these credentials.
          export_default_credentials: true
      - run: gcloud firebase test android run \
              --type robo \
              --app app-debug-unaligned.apk \
              --device model=Nexus6,version=21,locale=en,orientation=portrait  \
              --device model=Nexus7,version=19,locale=fr,orientation=landscape \
              --timeout 90s
